version: "3"
services:
  back-end:
    build: .
    ports:
      - 1001:3001
    volumes:
      - .:/home/back
  bd:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=testes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=junior123
    ports:
      - "1002:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 1003:8080